version: '3.9'

services:
  postgres:
    container_name: gamelist_docker
    image: bitnami/postgresql:latest
    ports:
      - '5431:5432'
    environment:
      - POSTGRES_USER=postgre
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gamelist_db
    volumes:
      - gamelist_pg_data:/bitnami/postgresql

volumes:
  pixproject_pg_data: